namespace SpriteKind {
    export const enemyBullet = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f f 2 f e f . . 
        . . f f f 2 f e e 2 2 f f f . . 
        . . f e 2 f f e e 2 f e e f . . 
        . f f e f f e e e f e e e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . . e f f f f f f f f 4 e . . 
        . . . 4 f 2 2 2 2 2 e d d 4 . . 
        . . . e f f f f f f e e 4 . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e f 2 f f f 2 f 2 e f . . 
        . . f f f 2 2 e e f 2 f f f . . 
        . . f e e f 2 e e f f 2 e f . . 
        . f f e e e f e e e f f e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f e . . . 
        . . 4 d d e 2 2 2 2 2 f 4 . . . 
        . . . 4 e e f f f f f f e . . . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    true
    )
    face = 0
})
function enemyWake () {
	
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite, 0, 0)
    timer.after(400, function () {
        controller.moveSprite(mySprite, 100, 100)
    })
    if (face == 3) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . f f f f f f . . . . . . 
            . . f f e e e e f 2 f . . . . . 
            . f f e e e e f 2 2 2 f . . . . 
            . f e e e f f e e e e f . . . . 
            . f f f f e e 2 2 2 2 e f . . . 
            . f e 2 2 2 f f f f e 2 f . . . 
            f f f f f f f e e e f f . . . . 
            f f e 4 4 e b f 4 4 e . . . . . 
            f e e 4 d 4 1 f d d e e . . . . 
            . f e e e 4 d d d e d d e . . . 
            . . f f e e 4 4 e 4 d d e . . . 
            . . . f 2 2 2 2 4 4 e e . . . . 
            . . . f 2 2 2 2 e 2 f . . . . . 
            . . . f 4 4 4 4 5 5 f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . f f f . . . . . . . . 
            `,img`
            . . . . . . . f f f . . . . . . 
            . . . . f f f f f 2 f . . . . . 
            . . f f e e e e e 2 2 f f . . . 
            . f f e e e e e e 2 2 2 f f . . 
            . f e e e e f f f e e e e f . . 
            . f f f f f e e e 2 2 2 2 e f . 
            f f f e 2 2 2 f f f f f e 2 f . 
            f f f f f f f f f e e e f f f . 
            f e f e 4 4 e b b f 4 4 e e f . 
            . f e e 4 d 4 b b f d d e f . . 
            . . f e e e 4 d d d d d f e e c 
            . . . f 2 2 2 2 2 2 2 e e d d c 
            . . . f 4 4 4 4 4 5 e 4 4 d d c 
            . . . f f f f f f f f e e e e . 
            . . . f f f . . . f f . . . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . f f . . . . . . . 
            . . . . f f f f 2 f f . . . . . 
            . . f f e e e e f 2 f f . . . . 
            . f f e e e e e f 2 2 f f . . . 
            . f e e e e f f e e e e f . . . 
            . f f f f f e e 2 2 2 2 e f . . 
            f f f e 2 2 2 f f f f e 2 f . . 
            f f f f f f f f e e e f f f . . 
            f e f e 4 4 e b f 4 4 e e f . . 
            . f e e 4 d 4 b f d d e f . . . 
            . . f e e e 4 d d d e e . . . . 
            . . . f 2 2 2 2 e e d d e . . . 
            . . . f 4 4 4 e 4 4 d d e . . . 
            . . . f f f f f e e e e . . . . 
            . . f f f f f f f f . . . . . . 
            . . f f f . . f f . . . . . . . 
            `,img`
            . . . . f f f f f f . . . . . . 
            . . f f e e e e f 2 f . . . . . 
            . f f e e e e f 2 2 2 f . . . . 
            . f e e e f f e e e e f . . . . 
            . f f f f e e 2 2 2 2 e f . . . 
            . f e 2 2 2 f f f f e 2 f . . . 
            f f f f f f f e e e f f f . . . 
            f f e 4 4 e b f 4 4 e e f . . . 
            f e e 4 d 4 1 f d d e f . . . . 
            . f e e e 4 d d d d f . . . . . 
            . . f d d e 4 4 4 e f . . . . . 
            . . f d d e 2 2 4 4 f . . . . . 
            . . . e e f 2 2 e 2 f . . . . . 
            . . . f 4 4 4 4 5 5 f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . f f f . . . . . . . . 
            `],
        100,
        false
        )
        projectile2 = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .............c..........
            .............ccccccc....
            .............cddddd.....
            .............ccccc......
            .............c..........
            ........................
            `, mySprite, 0, 0)
        projectile2.x += 4
        animation.runImageAnimation(
        projectile2,
        [img`
            ........................
            ........................
            ........................
            ........................
            ...............cc.......
            ..............cdc.......
            .............cddc.......
            ............cddc........
            ...........cddc.........
            ...........cdc..........
            ...........ccc..........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ..............11111.....
            ...............11111....
            ................11111...
            .................111cc..
            .................1ccdc..
            ................ccddcc..
            ...............cdddc....
            ...............cdcc.....
            ...............ccc......
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .............c..........
            .............ccccccc....
            .............cddddd.....
            .............ccccc......
            .............c..........
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    } else if (face == 2) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . f f f f f f . . . . 
            . . . . . f 2 f e e e e f f . . 
            . . . . f 2 2 2 f e e e e f f . 
            . . . . f e e e e f f e e e f . 
            . . . f e 2 2 2 2 e e f f f f . 
            . . . f 2 e f f f f 2 2 2 e f . 
            . . . . f f e e e f f f f f f f 
            . . . . . e 4 4 f b e 4 4 e f f 
            . . . . e e d d f 1 4 d 4 e e f 
            . . . e d d e d d d 4 e e e f . 
            . . . e d d 4 e 4 4 e e f f . . 
            . . . . e e 4 4 2 2 2 2 f . . . 
            . . . . . f 2 e 2 2 2 2 f . . . 
            . . . . . f 5 5 4 4 4 4 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . . f f f . . . . . 
            `,img`
            . . . . . . f f f . . . . . . . 
            . . . . . f 2 f f f f f . . . . 
            . . . f f 2 2 e e e e e f f . . 
            . . f f 2 2 2 e e e e e e f f . 
            . . f e e e e f f f e e e e f . 
            . f e 2 2 2 2 e e e f f f f f . 
            . f 2 e f f f f f 2 2 2 e f f f 
            . f f f e e e f f f f f f f f f 
            . f e e 4 4 f b b e 4 4 e f e f 
            . . f e d d f b b 4 d 4 e e f . 
            c e e f d d d d d 4 e e e f . . 
            c d d e e 2 2 2 2 2 2 2 f . . . 
            c d d 4 4 e 5 4 4 4 4 4 f . . . 
            . e e e e f f f f f f f f . . . 
            . . . . . f f . . . f f f . . . 
            . . . . . . . . . . . . . . . . 
            `,img`
            . . . . . . . f f . . . . . . . 
            . . . . . f f 2 f f f f . . . . 
            . . . . f f 2 f e e e e f f . . 
            . . . f f 2 2 f e e e e e f f . 
            . . . f e e e e f f e e e e f . 
            . . f e 2 2 2 2 e e f f f f f . 
            . . f 2 e f f f f 2 2 2 e f f f 
            . . f f f e e e f f f f f f f f 
            . . f e e 4 4 f b e 4 4 e f e f 
            . . . f e d d f b 4 d 4 e e f . 
            . . . . e e d d d 4 e e e f . . 
            . . . e d d e e 2 2 2 2 f . . . 
            . . . e d d 4 4 e 4 4 4 f . . . 
            . . . . e e e e f f f f f . . . 
            . . . . . . f f f f f f f f . . 
            . . . . . . . f f . . f f f . . 
            `,img`
            . . . . . . f f f f f f . . . . 
            . . . . . f 2 f e e e e f f . . 
            . . . . f 2 2 2 f e e e e f f . 
            . . . . f e e e e f f e e e f . 
            . . . f e 2 2 2 2 e e f f f f . 
            . . . f 2 e f f f f 2 2 2 e f . 
            . . . f f f e e e f f f f f f f 
            . . . f e e 4 4 f b e 4 4 e f f 
            . . . . f e d d f 1 4 d 4 e e f 
            . . . . . f d d d d 4 e e e f . 
            . . . . . f e 4 4 4 e d d f . . 
            . . . . . f 4 4 2 2 e d d f . . 
            . . . . . f 2 e 2 2 f e e . . . 
            . . . . . f 5 5 4 4 4 4 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . . f f f . . . . . 
            `],
        100,
        false
        )
        projectile2 = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........c.............
            ....ccccccc.............
            .....dddddc.............
            ......ccccc.............
            ..........c.............
            ........................
            `, mySprite, 0, 0)
        projectile2.x += -4
        animation.runImageAnimation(
        projectile2,
        [img`
            ........................
            ........................
            ........................
            ........................
            .......cc...............
            .......cdc..............
            .......cddc.............
            ........cddc............
            .........cddc...........
            ..........cdc...........
            ..........ccc...........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            .....11111..............
            ....11111...............
            ...11111................
            ..cc111.................
            ..cdcc1.................
            ..ccddcc................
            ....cdddc...............
            .....ccdc...............
            ......ccc...............
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ..........c.............
            ....ccccccc.............
            .....dddddc.............
            ......ccccc.............
            ..........c.............
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    } else if (face == 1) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d 4 e f f . . 
            . . f f e e 4 4 4 e d d 4 e . . 
            . . f 4 f 2 2 2 2 e d d e . . . 
            . . . . f 2 2 c c c e e . . . . 
            . . . . f 4 4 c d c 4 f . . . . 
            . . . . f f f d d c f f . . . . 
            . . . . . f d d c f f . . . . . 
            `,img`
            . . . . . . . f f . . . . . . . 
            . . . . . f f 2 2 f f . . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f 2 2 2 2 2 2 f f f . . 
            . . f f f 2 2 2 2 2 2 f f f . . 
            . . f e e e e e e e e e e f f . 
            . f f e 2 2 2 2 2 2 2 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f f . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . f f e 4 d d d d 4 e f e . . 
            . . f e f 2 2 2 2 2 f 4 e . . . 
            . . f 4 f 4 4 5 5 4 f 4 e . . . 
            . . . . f f f f f f d d e . . . 
            . . . . . f f f f e d d e . . . 
            . . . . . . . . . . e e . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 d d d d d d 4 e e f . 
            . . f e e d d d d d 4 e e f f e 
            . . f f e e 4 4 4 4 e e 4 f d d 
            . . f 4 f 2 2 2 2 2 2 f 1 e d d 
            . . . f f 2 2 2 2 2 2 f 4 4 e e 
            . . . . f 4 4 5 5 4 4 f . . . . 
            . . . . f f f f f f f f . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f e e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `],
        100,
        false
        )
        projectile2 = sprites.createProjectileFromSprite(img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ......ccccc.....
            .......cdc......
            .......cdc......
            .......cdc......
            .......cdc......
            ........dc......
            .........c......
            ................
            ................
            ................
            ................
            ................
            ................
            `, mySprite, 0, 0)
        projectile2.y += 4
        animation.runImageAnimation(
        projectile2,
        [img`
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .....ccc.........
            .....cdc.........
            .....ddc.........
            ....ddc..........
            ..cddc...........
            ..cdc............
            ..cc.............
            .................
            .................
            `,img`
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            ...1...ccc.......
            ...11.cc1cc......
            ...11..c1c.......
            ...1111c1c.......
            ...1111c1c.......
            ....111c1c.......
            ........1c.......
            .........c.......
            `,img`
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            ...........ccc...
            ..........cddc...
            .........cddc1...
            .......ccddc11...
            .......cddc111...
            .......ccc1111...
            ..........111....
            .........111.....
            .................
            .................
            .................
            .................
            .................
            `,img`
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            `],
        100,
        false
        )
    } else if (face == 0) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f . . . . . . . 
            . . . f f e e e e f f . . . . . 
            . . f e e e f f e e e f . . . . 
            . . f f f f 2 2 f f f f . . . . 
            . f f e 2 e 2 2 e 2 e f f . . . 
            . f e 2 f 2 f f f 2 f e f . . . 
            . f f f 2 f e e 2 2 f f f . . . 
            . f e 2 f f e e 2 f e e f . . . 
            f f e f f e e e f e e e f . . . 
            f f e e e e e e e e e e f . . . 
            . . f e e e e e e e e f f . . . 
            . . e f f f f f f f f 4 f . . . 
            . . 4 f 2 2 2 2 2 e d d f . . . 
            . . e f f f f f f e e 4 f . . . 
            . . . f f f . . f f . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . f f f f . . . . . . . 
            . . . f f e e e e f f . . . . . 
            . . f e e e f f e e e f . . . . 
            . . f f f f 2 2 f f f f . . . . 
            . f f e 2 e 2 2 e 2 e f f . . . 
            . f e 2 f 2 f f f 2 f e f . . . 
            . f f f 2 f e e 2 2 f f f . . . 
            . f e 2 f f e e 2 f e e f . . . 
            f f e f f e e e f e e e f . . . 
            f f e e e e e e e e e e f . . . 
            . . f e e e e e e e e f f . . . 
            . e e f f f f f f f f e e . . . 
            e 4 4 f 2 2 2 2 2 2 f 4 e . . . 
            e 4 4 f f f f f f f f . . . . . 
            . . . f f f . f f f . . . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `],
        100,
        false
        )
        projectile2 = sprites.createProjectileFromSprite(img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ......ccccc.....
            .......cdc......
            .......cdc......
            .......cdc......
            .......cdc......
            ........dc......
            .........c......
            ................
            ................
            ................
            ................
            ................
            ................
            `, mySprite, 0, 0)
        projectile2.y += -4
        animation.runImageAnimation(
        projectile2,
        [img`
            .................
            .................
            ..cc.............
            ..cdc............
            ..cddc...........
            ....ddc..........
            .....ddc.........
            .....cdc.........
            .....ccc.........
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            `,img`
            .........c.......
            ........1c.......
            ....111c1c.......
            ...1111c1c.......
            ...1111c1c.......
            ...11..c1c.......
            ...11.cc1cc......
            ...1...ccc.......
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            `,img`
            .................
            .................
            .................
            .................
            .................
            .........111.....
            ..........111....
            .......ccc1111...
            .......cddc111...
            .......ccddc11...
            .........cddc1...
            ..........cddc...
            ...........ccc...
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            `,img`
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            .................
            `],
        100,
        false
        )
    }
})
controller.down.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    mySprite.setImage(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d e e e e e f . . . 
        . . . f e 4 e d d 4 f . . . . . 
        . . . f 2 2 e d d e f . . . . . 
        . . f f 5 5 f e e f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `,img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e d d 4 . . . . 
        . . . f 2 2 2 2 e d d e . . . . 
        . . f f 5 5 4 4 f e e f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    100,
    true
    )
    face = 2
})
controller.right.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    mySprite.setImage(img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `)
})
controller.left.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    mySprite.setImage(img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . 4 d d e 4 4 4 e f . . . 
        . . . . e d d e 2 2 2 2 f . . . 
        . . . . f e e f 4 4 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `],
    100,
    true
    )
    face = 3
})
controller.up.onEvent(ControllerButtonEvent.Released, function () {
    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    mySprite.setImage(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    true
    )
    face = 1
})
info.onLifeZero(function () {
    game.setGameOverMessage(true, "GAME OVER!")
    game.setGameOverPlayable(true, music.melodyPlayable(music.wawawawaa), false)
    game.setGameOverEffect(true, effects.dissolve)
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.warmRadial, 500)
    scene.cameraShake(4, 500)
    sprites.destroy(sprite)
    info.changeScoreBy(10000)
})
let Enemy_projectile: Sprite = null
let projectile2: Sprite = null
let enemy1: Sprite = null
let mySprite: Sprite = null
let face = 0
face = 0
tiles.setCurrentTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.purpleInnerSouthEast)
scene.cameraFollowSprite(mySprite)
mySprite.setStayInScreen(true)
controller.moveSprite(mySprite)
namespace userconfig {
    export const ARCADE_SCREEN_WIDTH = 270
    export const ARCADE_SCREEN_HEIGHT = 240
}
let statusbar = statusbars.create(120, 10, StatusBarKind.Health)
statusbar.setLabel("HP")
statusbar.setColor(2, 15)
statusbar.setPosition(63, 8)
for (let index = 0; index < 29; index++) {
    enemy1 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    tiles.placeOnRandomTile(enemy1, sprites.dungeon.floorDark2)
}
game.onUpdateInterval(2000, function () {
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        if (spriteutils.distanceBetween(mySprite, value) <= 70) {
            value.follow(mySprite, 30)
            animation.runImageAnimation(
            value,
            [img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .....fffc1111111f.......
                ...fc111cd1111111f......
                ...f1b1b1b1111dddf......
                ...fbfbffcf11fcddf......
                ......fcf111111bbf......
                .......ccbdb1b1fcf......
                .......fffbfbfdff.......
                ........ffffffff........
                ........fffffffffff.....
                .........fffffc111cf....
                .........fffff1b1b1f....
                ..........ffffbfbfbf....
                ...........ffff.........
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ....7.fd11111111df......
                ...7..fd11111111df......
                ...7..fd11111111df......
                ...7..fddd1111dddff.....
                ...77.fbdbfddfbdbfcf....
                ...777fcdcf11fcdcfbf....
                ....77fffbdb1bdffcf.....
                ....fcb1bcffffff........
                ....f1c1c1ffffff........
                ....fdfdfdfffff.........
                .....f.f.f..............
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd111111111f......
                ......fd11111111df......
                ......fd11111111df......
                ......fcdd1111ddcff.....
                .......fbcf11fcbfbbf....
                .......ffbdb1bdffff.....
                ........fcbfbfdf........
                ........ffffffff........
                ......ffffffffff........
                .....fcb1bcffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fdd111111ddf......
                ......fbdd1111dddf......
                ......fcdbfddfbdbf......
                .......fbcf11fcbfff.....
                .......ffb1111bcfbcf....
                ........fcdb1bdfbbbf....
                .......ffffffffffcf.....
                .....fcb1bcfffff........
                .....f1b1b1ffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fd11111111df......
                ......fddd1111dddf......
                ......fbdbfddfbdbf......
                ......fcdcf11fcdcf......
                .......fb111111bf.......
                ......fffcdb1bdffff.....
                ....fc111cbfbfc111cf....
                ....f1b1b1ffff1b1b1f....
                ....fbfbffffffbfbfbf....
                .........ffffff.........
                ...........fff..........
                ........................
                ........................
                ........................
                ........................
                `],
            100,
            false
            )
            timer.after(500, function () {
                for (let index = 0; index < 4; index++) {
                    Enemy_projectile = sprites.createProjectileFromSprite(img`
                        . 1 1 . . . . . 
                        1 1 1 . . . . . 
                        1 1 1 1 . . . . 
                        . . 1 1 1 . . . 
                        . . . 1 1 1 . . 
                        . . . . 1 1 1 1 
                        . . . . . 1 1 1 
                        . . . . . 1 1 . 
                        `, value, randint(100, -100), randint(100, -100))
                    Enemy_projectile.setKind(SpriteKind.enemyBullet)
                    animation.runImageAnimation(
                    Enemy_projectile,
                    [img`
                        . 1 1 . . . . . 
                        1 1 1 . . . . . 
                        1 1 1 1 . . . . 
                        . . 1 1 1 . . . 
                        . . . 1 1 1 . . 
                        . . . . 1 1 1 1 
                        . . . . . 1 1 1 
                        . . . . . 1 1 . 
                        `,img`
                        . 1 1 . . 1 1 . 
                        . 1 1 1 1 1 1 . 
                        . . 1 1 1 1 . . 
                        . . . 1 1 . . . 
                        . . . 1 1 . . . 
                        . . 1 1 1 1 . . 
                        . 1 1 1 1 1 1 . 
                        . 1 1 . . 1 1 . 
                        `,img`
                        . . . . . 1 1 . 
                        . . . . . 1 1 1 
                        . . . . 1 1 1 1 
                        . . . 1 1 1 . . 
                        . . 1 1 1 . . . 
                        1 1 1 1 . . . . 
                        1 1 1 . . . . . 
                        . 1 1 . . . . . 
                        `,img`
                        . . . . . . . . 
                        1 1 . . . . 1 1 
                        1 1 1 . . 1 1 1 
                        . 1 1 1 1 1 1 . 
                        . 1 1 1 1 1 1 . 
                        1 1 1 . . 1 1 1 
                        1 1 . . . . 1 1 
                        . . . . . . . . 
                        `],
                    100,
                    true
                    )
                }
            })
        } else {
            value.follow(mySprite, 0)
        }
    }
})
